version: '3.8'
services:
  dbwordpress:
    container_name: wordpressdb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: wpdatabase
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: "654321"
    volumes:
      - "C:/Docker/wordpress/mysql:/var/lib/mysql"

  webwordpress:
    container_name: wordpressweb
    image: wordpress
    restart: always
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_HOST: dbwordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: "654321"
      WORDPRESS_DB_NAME: wpdatabase
    volumes:
      - "C:/Docker/wordpress/www:/var/www/html"
    depends_on:
      - dbwordpress


